#dev specific values
environment: dev

serviceAccount:
  create: false
  name: nginx
  annotations:
    eks.amazonaws.com/role-arn: ""

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80