name:  Dev deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REPO_NAME: ${{ github.event.repository.name }}
  IMAGE_TAG: ${{ github.sha }}
  CLUSTER_NAME: "dev-k8s"
  ENVIRONMENT: "dev"
  ECR_REPO: "nginx"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_PIPELINE_ROLE: ${{ secrets.AWS_PIPELINE_ROLE }}

jobs:
  build-image:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup helmfile
      uses: mamezou-tech/setup-helmfile@v0.8.0
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af
      with:
        role-to-assume: ${{ env.AWS_PIPELINE_ROLE }}
        aws-region: ${{ env.AWS_DEFAULT_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Kubernetes deployment
      run: |
        aws eks update-kubeconfig --name $CLUSTER_NAME
        IMAGE_TAG=${IMAGE_TAG} helmfile -e ${ENVIRONMENT} -f helm/nginx/helmfile.yaml apply
